// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/5/2025, 3:35:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/juliendecruydt/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/plugins/**/*.{js,ts,mjs}","/Users/juliendecruydt/Documents/portfolio/composables/**/*.{js,ts,mjs}","/Users/juliendecruydt/Documents/portfolio/utils/**/*.{js,ts,mjs}","/Users/juliendecruydt/Documents/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/juliendecruydt/Documents/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;